### ISSUE TITLE
Is the project still available and working?

### ISSUE THREAD

**Issue by ManuEZ** [ChrisMichaelPerezSantiago/animefreak#2]
Hey there, I read that there's a problem with the mp4 src. I would like to know if the project is working and available, thank you.

**Comment by chrismichaelps** [comment]
Hello @ManuEZ,

Currently the project has not been maintained for a long time, therefore I cannot tell you if it still works correctly. And I don't think time will allow me now. Since I dedicate all my time to my personal job.
